// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeiBjh1n2a3QYE_MQAGUR5iZlvxTivxnY',
    appId: '1:193337063120:web:4b155c150fbb9747a490d5',
    messagingSenderId: '193337063120',
    projectId: 'kigaliserviceapp',
    authDomain: 'kigaliserviceapp.firebaseapp.com',
    storageBucket: 'kigaliserviceapp.firebasestorage.app',
    measurementId: 'G-LLDNMV2999',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkIye6YuU-gqMOJDGys8hAs-rV2ht_xmg',
    appId: '1:324083063568:android:0f4ece29c9939a32a6a395',
    messagingSenderId: '324083063568',
    projectId: 'kigali-service-app',
    storageBucket: 'kigali-service-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcpxJ_6BvQhB_9PIxXKqUW-vAlmreF2u4',
    appId: '1:193337063120:ios:91db16074b227e6fa490d5',
    messagingSenderId: '193337063120',
    projectId: 'kigaliserviceapp',
    storageBucket: 'kigaliserviceapp.firebasestorage.app',
    iosBundleId: 'com.example.kigaliCityServices',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcpxJ_6BvQhB_9PIxXKqUW-vAlmreF2u4',
    appId: '1:193337063120:ios:91db16074b227e6fa490d5',
    messagingSenderId: '193337063120',
    projectId: 'kigaliserviceapp',
    storageBucket: 'kigaliserviceapp.firebasestorage.app',
    iosBundleId: 'com.example.kigaliCityServices',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAeiBjh1n2a3QYE_MQAGUR5iZlvxTivxnY',
    appId: '1:193337063120:web:fd222663f5be9b94a490d5',
    messagingSenderId: '193337063120',
    projectId: 'kigaliserviceapp',
    authDomain: 'kigaliserviceapp.firebaseapp.com',
    storageBucket: 'kigaliserviceapp.firebasestorage.app',
    measurementId: 'G-WM3LBSMBVW',
  );
}
